// Code generated by "stringer -type=AVFieldOrder -trimprefix=AV_FIELD_"; DO NOT EDIT.

package mediafileinfo

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AV_FIELD_UNKNOWN-0]
	_ = x[AV_FIELD_PROGRESSIVE-1]
	_ = x[AV_FIELD_TT-2]
	_ = x[AV_FIELD_BB-3]
	_ = x[AV_FIELD_TB-4]
	_ = x[AV_FIELD_BT-5]
}

const _AVFieldOrder_name = "UNKNOWNPROGRESSIVETTBBTBBT"

var _AVFieldOrder_index = [...]uint8{0, 7, 18, 20, 22, 24, 26}

func (i AVFieldOrder) String() string {
	if (i < 0) || (i >= AVFieldOrder(len(_AVFieldOrder_index)-1)) {
		return "UNKNOWN"
	}
	return _AVFieldOrder_name[_AVFieldOrder_index[i]:_AVFieldOrder_index[i+1]]
}
