// Code generated by "stringer -type=AVMediaType -trimprefix=AVMEDIA_TYPE_"; DO NOT EDIT.

package mediafileinfo

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AVMEDIA_TYPE_UNKNOWN - -1]
	_ = x[AVMEDIA_TYPE_VIDEO-1]
	_ = x[AVMEDIA_TYPE_AUDIO-2]
	_ = x[AVMEDIA_TYPE_DATA-3]
	_ = x[AVMEDIA_TYPE_SUBTITLE-4]
	_ = x[AVMEDIA_TYPE_ATTACHMENT-5]
	_ = x[AVMEDIA_TYPE_NB-6]
}

const (
	_AVMediaType_name_0 = "UNKNOWN"
	_AVMediaType_name_1 = "VIDEOAUDIODATASUBTITLEATTACHMENTNB"
)

var (
	_AVMediaType_index_1 = [...]uint8{0, 5, 10, 14, 22, 32, 34}
)

func (i AVMediaType) String() string {
	switch {
	case i == -1:
		return _AVMediaType_name_0
	case 1 <= i && i <= 6:
		i -= 1
		return _AVMediaType_name_1[_AVMediaType_index_1[i]:_AVMediaType_index_1[i+1]]
	default:
		return _AVMediaType_name_0
	}
}
