name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22' # oder deine Go-Version

    - name: Install FFmpeg (Ubuntu)
      run: sudo apt-get update && sudo apt-get install -y ffmpeg libavformat-dev libavutil-dev

    - name: Run tests with coverage
      run: |
        go test -v -coverprofile=coverage.out ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: coverage.out
        flags: unittests
        token: ${{ secrets.CODECOV_TOKEN }} # nur nötig für private Repos

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}